#!/usr/bin/python
"""Run all scripts found in the Munki postflight.d directory."""


import sys

sys.path.append('/usr/local/sal')
import utils


POSTFLIGHT_DIR = '/usr/local/munki/postflight.d'


def main():
    utils.run_scripts(POSTFLIGHT_DIR, sys.argv[1])


if __name__ == "__main__":
    main()