#!/usr/local/sal/Python.framework/Versions/Current/bin/python3
"""Run all scripts found in the Munki preflight.d directory."""


import sys

import sal


PREFLIGHT_DIR = '/usr/local/munki/preflight.d'


def main():
    try:
        sal.run_scripts(PREFLIGHT_DIR, sys.argv[1], error=True)
    except RuntimeError as e:
        sys.exit(e)


if __name__ == "__main__":
    main()
