#!/usr/bin/python
"""Run all scripts found in the Munki preflight.d directory."""


import sys

sys.path.append('/usr/local/sal')
import utils


PREFLIGHT_DIR = '/usr/local/munki/preflight.d'


def main():
    utils.run_scripts(PREFLIGHT_DIR, sys.argv[1])


if __name__ == "__main__":
    main()
