#!/usr/local/sal/Python.framework/Versions/3.8/bin/python3
"""Run all scripts found in the Munki preflight.d directory."""


import sys

import sal


PREFLIGHT_DIR = '/usr/local/munki/preflight.d'


def main():
    sal.run_scripts(PREFLIGHT_DIR, sys.argv[1])


if __name__ == "__main__":
    main()
