#!/usr/local/sal/Python.framework/Versions/Current/bin/python3
"""preflight

Retrieves plugin scripts to run on client.
"""


import argparse
import json
import os
import pathlib
import shutil
import sys
import urllib

import sal
sys.path.append('/usr/local/munki')
from munkilib import munkicommon


EXTERNAL_SCRIPTS_DIR = '/usr/local/sal/external_scripts'


def main():
    set_verbosity()

    if sal.pref('SyncScripts') == True:
        if not os.path.exists(EXTERNAL_SCRIPTS_DIR):
            os.makedirs(EXTERNAL_SCRIPTS_DIR)
        server_scripts = get_checksum()
        if server_scripts:
            create_dirs(server_scripts)
            download_scripts(server_scripts)

        cleanup_old_scripts(server_scripts)
        remove_empty_folders(EXTERNAL_SCRIPTS_DIR)


def get_prefs():
    # Check for mandatory prefs and bail if any are missing.
    required_prefs = {}
    required_prefs["key"] = sal.pref('key')
    required_prefs["ServerURL"] = sal.pref('ServerURL').rstrip('/')

    for key, val in required_prefs.items():
        if not val:
            sys.exit(f'Required Sal preference "{key}" is not set.')
    return required_prefs


def get_checksum():
    """Downloads the checksum of existing scripts.

    Returns:
        A dict with the script name, plugin name and hash of the script
        or None if no external scripts are used.
    """
    preflight_url = f"{sal.pref('ServerURL')}/preflight-v2/"
    stdout, stderr = sal.send_report(preflight_url, form_data={'os_family': 'Darwin'})

    if stderr:
        munkicommon.display_debug2(stderr)
    stdout_list = stdout.split("\n")
    if "<h1>Page not found</h1>" not in stdout_list:
        munkicommon.display_debug2(stdout)

    try:
        return json.loads(stdout)
    except:
        munkicommon.display_debug2("Didn't receive valid JSON.")
        return None


def download_scripts(server_scripts):
    """Checksum local scripts and if no matches, download."""
    for server_script in server_scripts:
        download_required = False
        target_script = os.path.join(
            EXTERNAL_SCRIPTS_DIR, server_script['plugin'], server_script['filename'])
        if not os.path.exists(target_script):
            download_required = True
        else:
            local_hash = sal.get_hash(target_script)
            if local_hash != server_script['hash']:
                download_required = True

        if download_required == True:
            munkicommon.display_debug2(f'downloading {server_script["filename"]}')
            download_and_write_script(server_script)


def download_and_write_script(server_script):
    """Gets script from the server and makes it execuatble."""
    script_url = (
        f"{sal.pref('ServerURL')}/preflight-v2/get-script/"
        f"{server_script['plugin']}/{server_script['filename']}/")
    stdout, stderr = sal.curl(script_url)
    if stderr:
        munkicommon.display_debug2('Error received downloading script:')
        munkicommon.display_debug2(stderr)

    script = open(
        os.path.join(EXTERNAL_SCRIPTS_DIR, server_script['plugin'], server_script['filename']),
        'w')
    try:
        data = json.loads(stdout)
    except:
        munkicommon.display_debug2('Did not receive valid JSON when requesting script content.')
        return False

    script.write(data[0]['content'])
    script.close()
    os.chmod(
        os.path.join(EXTERNAL_SCRIPTS_DIR, server_script['plugin'], server_script['filename']),
        0o755)


def create_dirs(server_scripts):
    """Creates any directories needed for external scripts

    Directories are named after the plugin.
    """
    for item in server_scripts:
        (pathlib.Path(EXTERNAL_SCRIPTS_DIR) / item['plugin']).mkdir(parents=True, exist_ok=True)


def cleanup_old_scripts(server_scripts):
    """Finds and removes scripts on disk that aren't needed anymore."""
    if server_scripts == None:
        # No scripts from the server, nail the whole thing
        shutil.rmtree(EXTERNAL_SCRIPTS_DIR)
    else:
        keep = []
        for server_script in server_scripts:
            keep.append(os.path.join(EXTERNAL_SCRIPTS_DIR, server_script['plugin'],
                                     server_script['filename']))

        for root, subFolders, files in os.walk(EXTERNAL_SCRIPTS_DIR):
            for script in files:
                if os.path.join(root, script) not in keep:
                    os.remove(os.path.join(root, script))


def remove_empty_folders(path):
    """Function to remove empty folders."""
    for root, dirs, files in os.walk(path,topdown=False):
         for name in dirs:
             fname = os.path.join(root,name)
             if not os.listdir(fname):
                 os.removedirs(fname)


def set_verbosity():
    """Set the verbosity based on options or munki verbosity level."""
    args = get_args()
    munkicommon.verbose = (
        5 if args.debug else int(os.environ.get('MUNKI_VERBOSITY_LEVEL', 0)))


def get_args():
    """Return commandline options."""
    parser = argparse.ArgumentParser()
    parser.add_argument("run_type")
    parser.add_argument(
        "-d", "--debug", default=False, action="store_true", help="Enable debug output.")
    # We have no arguments, so don't store the results.
    return parser.parse_args()


if __name__ == '__main__':
    main()
